apiVersion: v1
kind: Namespace
metadata:
  name: ns-dev
  labels:
    app: frontend
    env: dev
---
apiVersion: v1
kind: Secret
metadata:
  name: sm-parameters
  namespace: ns-dev
data:
  dbHost: ZGItZGV2LmNvbXBhbnkuY29t
  dbPort: MzMwNg==
  dbUser: dXNlci1yb290
  dbPass: M2xHaWdhbnRlMjAyNj8=
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rs-nginx-dev
  namespace: ns-dev
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      env: dev
      app: frontend
  template:
    metadata:
      labels:
        env: dev
        app: frontend
    spec:
      containers:
        - name: app-python
          image: python:3.7-alpine
          command:
            [
              "sh",
              "-c",
              "echo 'Pagina Python' > index.html && python -m http.server 9080",
            ]
          env:
            - name: TITLE
              value: "Frontend App"
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: sm-parameters
                  key: dbHost
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: sm-parameters
                  key: dbPort
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: sm-parameters
                  key: dbUser
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: sm-parameters
                  key: dbPass
