apiVersion: v1
kind: Namespace
metadata:
  name: ns-dev
  labels:
    app: frontend
    env: dev
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-parameters
  namespace: ns-dev
data:
  domain: http://dev-api.company.com
  apiUrlBase: /api/v1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rs-nginx-dev
  namespace: ns-dev
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      env: dev
      app: frontend
  template:
    metadata:
      labels:
        env: dev
        app: frontend
    spec:
      containers:
        - name: app-python
          image: python:3.7-alpine
          command:
            [
              "sh",
              "-c",
              "echo 'Pagina Python' > index.html && python -m http.server 9080",
            ]
          env:
            - name: TITLE
              value: "Frontend App"
            - name: DOMAIN
              valueFrom:
                configMapKeyRef:
                  name: cm-parameters
                  key: domain
            - name: API_URL
              valueFrom:
                configMapKeyRef:
                  name: cm-parameters
                  key: apiUrlBase
