apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: rs-nginx
spec:
  replicas: 5
  selector:
    matchLabels:
      env: dev
      app: frontend
  template:
    metadata:
      labels:
        env: dev
        app: frontend
    spec:
      containers:
        - name: app-python
          image: python:3.6-alpine
          command:
            [
              "sh",
              "-c",
              "echo 'Página Python' > index.html && python -m http.server 9080",
            ]
